### ISSUE TITLE
couple bugs/glitches

### ISSUE THREAD

**Issue by eiiiiix** [svennd/vita-chain#6]
ok
so there's a few bugs/glirches I've found
so I've been working on them (on my vita not github)

atoms speed up temporarily when atoms expand - fixed
atoms move out of bounds with 20+ on screen - appears to be fixed
game crashes when expanded atoms is more than level atoms - fixed?
fps drops to 0.5 when 30+ expanded - fixed, lowest dropped to now is 44
attoms get stuck in walls sometimes - working on a fix
lagg with 40+ atoms - fixed

bugs/glitches that I've caused with the fixes

level ends when atom merges
if a level need ex. 15 of 30
the 15th atom to expand will end the level when it merges
if I can't fix it then I will try to make it smoother

atom location randomiser returns nil
this was an accident 
should be an easy fix

expanded atoms stay 50% longer
also an accident 
simple fix too

these are currently offline but when I have time and I fix the ones I added ill put them on github and make a pull request

**Comment by svennd** [comment]
Hey eiiiiiiix,

Thanks for this :) ill be more then happy to merge your PR.

I haven't been giving the vita much love last months, with VitaGL blasting everyone away :)

Svenn

**Comment by eiiiiix** [comment]
I currently have everything fixed but the getting stuck in walls 
I even fixed the death spiral
in ~3 hours I can get it on github

**Comment by eiiiiix** [comment]
wait nevermind
150+ gives the death spiral
but it doesn't happen at 50+ anymore

**Comment by eiiiiix** [comment]
ok i just made the pull request
pretty sure it should be game.lua but index.lua is whats used by the app and i feel like shit rn
yesterday when i got home i felt like shit
if i didnt i wouldve made ithe pr sooner

**Comment by svennd** [comment]
Hey Eiiiiix,

Thanks for the PR, I will check it and include you in the copy, since you changed the names, its a bit harder for me to see what you changed. But thanks, and take care, your the 🥇 !

;)

**Comment by eiiiiix** [comment]
yeah the name change wasn't intentional
I was editing in vitashell on vita cuz it was faster
also vitashell glitched out and deleted a few random lines
I had to re add them but I didn't feel like retyping comments so some are missing

**Comment by svennd** [comment]
Hey Eiiiix,

Can you upload the latest game.lua ? index.lua is only the menu. I can't really find the differences.

Ofc I will add you to the credits.

thanks.

**Comment by eiiiiix** [comment]
was editing on vita so it was index.lua
game.lua is index.lua on the vita so i just absentmindedly uploaded without renaming
and it looks like the locals were taken out so im gonna fix that

**Comment by svennd** [comment]
not really sure what you changed, but I cannot find the code you have fixed. closing this for now... perhaps I play with the code some time soon.
